# Generated by Django 5.2.10 on 2026-02-02 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('role_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_firstname', models.CharField(max_length=255)),
                ('res_middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('res_lastname', models.CharField(max_length=255)),
                ('res_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('res_age', models.IntegerField()),
                ('res_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('res_email_address', models.CharField(max_length=255, unique=True)),
                ('res_password', models.CharField(max_length=255)),
                ('res_is_active', models.BooleanField(default=True)),
                ('res_last_login_at', models.DateTimeField(blank=True, null=True)),
                ('res_added_on', models.DateTimeField(auto_now_add=True)),
                ('res_updated_on', models.DateTimeField(blank=True, null=True)),
                ('res_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('res_is_deleted', models.BooleanField(default=False)),
                ('officials_id', models.IntegerField(blank=True, null=True)),
                ('res_location', models.CharField(blank=True, max_length=255, null=True)),
                ('res_role', models.ForeignKey(db_column='res_role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='residents.role')),
            ],
            options={
                'db_table': 'residents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=255)),
                ('admin_password', models.CharField(max_length=255)),
                ('admin_contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_email_address', models.CharField(max_length=255, unique=True)),
                ('admin_role', models.ForeignKey(db_column='admin_role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='residents.role')),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
    ]
