# Generated by Django 5.2.10 on 2026-02-06 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0002_official_delete_brgyofficial'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='officials_id',
            field=models.ForeignKey(blank=True, db_column='officials_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='officials.official'),
        ),
    ]
