# Generated by Django 5.2.10 on 2026-02-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_alter_resident_officials_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='officials_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
