# Generated by Django 5.2.10 on 2026-02-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('svc_id', models.AutoField(primary_key=True, serialize=False)),
                ('svc_name', models.CharField(max_length=255)),
                ('svc_email_address', models.CharField(max_length=255, unique=True)),
                ('svc_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('svc_password', models.CharField(max_length=255)),
                ('svc_location', models.CharField(blank=True, max_length=255, null=True)),
                ('svc_description', models.TextField(blank=True, null=True)),
                ('svc_is_active', models.BooleanField(default=True)),
                ('svc_added_on', models.DateTimeField(auto_now_add=True)),
                ('svc_updated_on', models.DateTimeField(blank=True, null=True)),
                ('svc_is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'services',
                'managed': True,
            },
        ),
    ]
