# Generated by Django 5.2.10 on 2026-02-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'managed': False},
        ),
    ]
