# Generated by Codex on 2026-02-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS services (
                    svc_id SERIAL PRIMARY KEY,
                    svc_name VARCHAR(255) NOT NULL,
                    svc_email_address VARCHAR(255) UNIQUE NOT NULL,
                    svc_contact_number VARCHAR(20),
                    svc_password VARCHAR(255) NOT NULL,
                    svc_location VARCHAR(255),
                    svc_description TEXT,
                    svc_is_active BOOLEAN DEFAULT TRUE,
                    svc_added_on TIMESTAMPTZ DEFAULT NOW(),
                    svc_updated_on TIMESTAMPTZ NULL,
                    svc_is_deleted BOOLEAN DEFAULT FALSE
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS services;",
        )
    ]
