# Generated by Codex on 2026-02-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_service_options"),
        ("services", "0002_create_services_if_missing"),
    ]

    operations = []
