# Generated by Django 5.2.10 on 2026-02-06 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0002_alter_resident_officials_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfAuthority',
            fields=[
                ('proof_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(db_column='res_id', on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='residents.resident')),
            ],
            options={
                'db_table': 'resident_proofs',
                'managed': True,
            },
        ),
    ]
