# Generated by Codex on 2026-02-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE resident_proofs
                    ADD COLUMN IF NOT EXISTS subject_role VARCHAR(50),
                    ADD COLUMN IF NOT EXISTS subject_email VARCHAR(255);
            """,
            reverse_sql="""
                ALTER TABLE resident_proofs
                    DROP COLUMN IF EXISTS subject_email,
                    DROP COLUMN IF EXISTS subject_role;
            """,
        )
    ]

