# Generated by Django 5.2.10 on 2026-02-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_admin_notifications'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE resident_proofs
                            ADD COLUMN IF NOT EXISTS subject_email VARCHAR(255),
                            ADD COLUMN IF NOT EXISTS subject_role VARCHAR(50);
                    """,
                    reverse_sql="""
                        ALTER TABLE resident_proofs
                            DROP COLUMN IF EXISTS subject_role,
                            DROP COLUMN IF EXISTS subject_email;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='proofofauthority',
                    name='subject_email',
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='proofofauthority',
                    name='subject_role',
                    field=models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
