# Generated by Django 5.2.10 on 2026-02-11 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_make_proof_resident_nullable'),
        ('residents', '0003_alter_resident_officials_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofauthority',
            name='resident',
            field=models.ForeignKey(blank=True, db_column='res_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='residents.resident'),
        ),
    ]
