# Generated by Codex on 2026-02-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_merge_0002_alter_service_options_0002_create_services_if_missing"),
        ("auth_app", "0005_make_proof_resident_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceDispatchNotification",
            fields=[
                ("dispatch_id", models.AutoField(primary_key=True, serialize=False)),
                ("report_id", models.IntegerField()),
                ("incident_type", models.CharField(max_length=20)),
                ("barangay", models.CharField(blank=True, max_length=255, null=True)),
                ("location_text", models.CharField(blank=True, max_length=500, null=True)),
                ("status", models.CharField(default="Dispatched", max_length=20)),
                ("sms_sent", models.BooleanField(default=False)),
                ("sms_error", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        db_column="svc_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_notifications",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "db_table": "service_dispatch_notifications",
                "managed": True,
            },
        ),
    ]
