# Generated by Codex on 2026-02-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0006_alter_proofofauthority_resident"),
        ("auth_app", "0006_servicedispatchnotification"),
    ]

    operations = []
