from django.urls import path
from .views import (
    signup,
    login,
    token_refresh,
    admin_me,
    admin_approvals,
    admin_approvals_update,
    admin_notifications,
    admin_notifications_read,
    admin_notifications_read_all,
    officials_residents_pending,
    officials_residents_approve,
    officials_residents_remove,
    officials_services_list,
    officials_services_registered,
    officials_services_create,
    officials_services_update,
    officials_services_delete,
    officials_dashboard,
    officials_reports_recent,
    officials_reports_all,
    officials_incidents_map,
    officials_reports_dispatch,
    officials_reports_dispatch_all,
    officials_notifications,
    officials_profile,
    officials_profile_update,
    officials_profile_avatar_update,
    officials_password_update,
    services_dispatch_notifications,
    services_dispatch_complete,
    services_profile,
    services_profile_update,
    services_profile_avatar_update,
    services_password_update,
    residents_incidents_create,
    residents_incidents_my,
    residents_newsfeed_create,
    residents_newsfeed_list,
    residents_newsfeed_interest,
    residents_newsfeed_save,
    residents_newsfeed_delete,
    residents_newsfeed_comment,
    residents_newsfeed_share,
    residents_profile,
    residents_profile_update,
    residents_profile_avatar_update,
    residents_password_update,
    ai_chat,
    logout,
)

urlpatterns = [
    path("signup/", signup, name="signup"),
    path("login/", login, name="login"),
    path("token/refresh/", token_refresh, name="token_refresh"),
    path("logout/", logout, name="logout"),
    path("admin/me/", admin_me, name="admin_me"),
    path("admin/approvals/", admin_approvals, name="admin_approvals"),
    path("admin/approvals/update/", admin_approvals_update, name="admin_approvals_update"),
    path("admin/notifications/", admin_notifications, name="admin_notifications"),
    path("admin/notifications/read/", admin_notifications_read, name="admin_notifications_read"),
    path("admin/notifications/read-all/", admin_notifications_read_all, name="admin_notifications_read_all"),
    path("officials/residents/pending/", officials_residents_pending, name="officials_residents_pending"),
    path("officials/residents/approve/", officials_residents_approve, name="officials_residents_approve"),
    path("officials/residents/remove/", officials_residents_remove, name="officials_residents_remove"),
    path("officials/services/", officials_services_list, name="officials_services_list"),
    path("officials/services/registered/", officials_services_registered, name="officials_services_registered"),
    path("officials/services/create/", officials_services_create, name="officials_services_create"),
    path("officials/services/update/", officials_services_update, name="officials_services_update"),
    path("officials/services/delete/", officials_services_delete, name="officials_services_delete"),
    path("officials/dashboard/", officials_dashboard, name="officials_dashboard"),
    path("officials/reports/recent/", officials_reports_recent, name="officials_reports_recent"),
    path("officials/reports/all/", officials_reports_all, name="officials_reports_all"),
    path("officials/incidents/map/", officials_incidents_map, name="officials_incidents_map"),
    path("officials/reports/dispatch/", officials_reports_dispatch, name="officials_reports_dispatch"),
    path("officials/reports/dispatch-all/", officials_reports_dispatch_all, name="officials_reports_dispatch_all"),
    path("officials/notifications/", officials_notifications, name="officials_notifications"),
    path("officials/profile/", officials_profile, name="officials_profile"),
    path("officials/profile/update/", officials_profile_update, name="officials_profile_update"),
    path("officials/profile/avatar/", officials_profile_avatar_update, name="officials_profile_avatar_update"),
    path("officials/profile/password/", officials_password_update, name="officials_password_update"),
    path("services/dispatches/", services_dispatch_notifications, name="services_dispatch_notifications"),
    path("services/dispatches/complete/", services_dispatch_complete, name="services_dispatch_complete"),
    path("services/profile/", services_profile, name="services_profile"),
    path("services/profile/update/", services_profile_update, name="services_profile_update"),
    path("services/profile/avatar/", services_profile_avatar_update, name="services_profile_avatar_update"),
    path("services/profile/password/", services_password_update, name="services_password_update"),
    path("residents/incidents/create/", residents_incidents_create, name="residents_incidents_create"),
    path("residents/incidents/my/", residents_incidents_my, name="residents_incidents_my"),
    path("residents/newsfeed/create/", residents_newsfeed_create, name="residents_newsfeed_create"),
    path("residents/newsfeed/list/", residents_newsfeed_list, name="residents_newsfeed_list"),
    path("residents/newsfeed/interest/", residents_newsfeed_interest, name="residents_newsfeed_interest"),
    path("residents/newsfeed/save/", residents_newsfeed_save, name="residents_newsfeed_save"),
    path("residents/newsfeed/delete/", residents_newsfeed_delete, name="residents_newsfeed_delete"),
    path("residents/newsfeed/comment/", residents_newsfeed_comment, name="residents_newsfeed_comment"),
    path("residents/newsfeed/share/", residents_newsfeed_share, name="residents_newsfeed_share"),
    path("residents/profile/", residents_profile, name="residents_profile"),
    path("residents/profile/update/", residents_profile_update, name="residents_profile_update"),
    path("residents/profile/avatar/", residents_profile_avatar_update, name="residents_profile_avatar_update"),
    path("residents/profile/password/", residents_password_update, name="residents_password_update"),
    path("ai/chat/", ai_chat, name="ai_chat"),
]
