from django.urls import path
from .views import (
    signup,
    login,
    token_refresh,
    admin_me,
    admin_approvals,
    admin_approvals_update,
    admin_notifications,
    admin_notifications_read,
    admin_notifications_read_all,
    officials_residents_pending,
    officials_residents_approve,
    officials_residents_remove,
    officials_services_list,
    officials_services_create,
    officials_services_update,
    officials_services_delete,
    officials_dashboard,
    officials_reports_recent,
    officials_reports_all,
    officials_incidents_map,
    ai_chat,
    logout,
)

urlpatterns = [
    path("signup/", signup, name="signup"),
    path("login/", login, name="login"),
    path("token/refresh/", token_refresh, name="token_refresh"),
    path("logout/", logout, name="logout"),
    path("admin/me/", admin_me, name="admin_me"),
    path("admin/approvals/", admin_approvals, name="admin_approvals"),
    path("admin/approvals/update/", admin_approvals_update, name="admin_approvals_update"),
    path("admin/notifications/", admin_notifications, name="admin_notifications"),
    path("admin/notifications/read/", admin_notifications_read, name="admin_notifications_read"),
    path("admin/notifications/read-all/", admin_notifications_read_all, name="admin_notifications_read_all"),
    path("officials/residents/pending/", officials_residents_pending, name="officials_residents_pending"),
    path("officials/residents/approve/", officials_residents_approve, name="officials_residents_approve"),
    path("officials/residents/remove/", officials_residents_remove, name="officials_residents_remove"),
    path("officials/services/", officials_services_list, name="officials_services_list"),
    path("officials/services/create/", officials_services_create, name="officials_services_create"),
    path("officials/services/update/", officials_services_update, name="officials_services_update"),
    path("officials/services/delete/", officials_services_delete, name="officials_services_delete"),
    path("officials/dashboard/", officials_dashboard, name="officials_dashboard"),
    path("officials/reports/recent/", officials_reports_recent, name="officials_reports_recent"),
    path("officials/reports/all/", officials_reports_all, name="officials_reports_all"),
    path("officials/incidents/map/", officials_incidents_map, name="officials_incidents_map"),
    path("ai/chat/", ai_chat, name="ai_chat"),
]
