# Generated by Codex on 2026-02-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("officials", "0003_brgyofficial_delete_official"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS brgy_officials (
                    official_id SERIAL PRIMARY KEY,
                    official_name VARCHAR(255) NOT NULL,
                    official_email_address VARCHAR(255) UNIQUE NOT NULL,
                    official_contact_number VARCHAR(20),
                    official_password VARCHAR(255) NOT NULL,
                    official_position VARCHAR(255),
                    official_barangay VARCHAR(255),
                    official_is_active BOOLEAN DEFAULT TRUE,
                    official_added_on TIMESTAMPTZ DEFAULT NOW(),
                    official_updated_on TIMESTAMPTZ NULL,
                    official_is_deleted BOOLEAN DEFAULT FALSE
                );
            """,
            reverse_sql="DROP TABLE IF EXISTS brgy_officials;",
        )
    ]
